// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZ4lVdBUC4RrQLGyF1aia25SjVknHV-E',
    appId: '1:703093520730:web:4516ed719e52f96fa99b63',
    messagingSenderId: '703093520730',
    projectId: 'mobiledevproject-ecam2022',
    authDomain: 'mobiledevproject-ecam2022.firebaseapp.com',
    storageBucket: 'mobiledevproject-ecam2022.appspot.com',
    measurementId: 'G-0L0ZHPCXMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj7rnPzn4GItEv0vZ6-crfBdIrSOg5xNo',
    appId: '1:703093520730:android:9ffdb32a814c9973a99b63',
    messagingSenderId: '703093520730',
    projectId: 'mobiledevproject-ecam2022',
    storageBucket: 'mobiledevproject-ecam2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTCJeOmAmNTbjhjFXDSHo0jP6w6Emxk0M',
    appId: '1:703093520730:ios:ee5775fe1fc4d7c4a99b63',
    messagingSenderId: '703093520730',
    projectId: 'mobiledevproject-ecam2022',
    storageBucket: 'mobiledevproject-ecam2022.appspot.com',
    iosClientId: '703093520730-h7e5l2mge4m1fhm8cklvpjtg1blnsbr7.apps.googleusercontent.com',
    iosBundleId: 'com.socialnetworkecam.app',
  );
}
